[ADD] - todo
selab-hs/selab-todo-list pull request #1
Opened 2022-07-31 15:59 UTC by HwangHarim

restful을 사용하여 Get/post/put/delete api를 구현했습니다.

2022-08-03 02:12 UTC, DongGeon0908 commented
README 작성해주세요

2022-08-03 02:30 UTC, DongGeon0908 requested changes
수정해보세요

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +  }
spring todo에서는 lombok 사용하셔도 됩니다!

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +})
swagger 사용할꺼면 모든 api에 대한 문서화 부탁드려요

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +  public ResponseEntity<?> postToDo(@RequestBody CreateToDoRequest createToDoRequest) {
와일드카드를 쓴 이유가 궁금합니다

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +    return new ResponseEntity<>("SUCCESS", HttpStatus.OK);
데이터를 생성할 때 사용하는 상태코드가 있어요!

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +  @PutMapping("/{id}")
Put이 좋을까요? 아니면 Patch가 좋을까요?

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/dto/response/ToDoResponse.java
> +@NoArgsConstructor
```suggestion
@Data
```

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/dto/response/ToDoResponse.java
> +  private LocalDateTime createDateTime;
불변하게 가도 될 것 같아요 final

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/dto/request/UpdateToDoRequest.java
> +@AllArgsConstructor
```suggestion
@Data
```

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/dto/request/CreateToDoRequest.java
> +@AllArgsConstructor
```suggestion
@Data
```

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/domain/ToDoList.java
> +  private LocalDateTime createdDateTime;
수정시간은 별도로 관리하지 않나요?
BaseEntity를 지운 이유가 궁금합니다

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +
메서드로 따로 뺄 필요가 없을 것 같네요

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +}
수정이 아니라 생성하는 건데??????

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +  }
너무 메서드로 분리하다 보니까 뭐가 뭔지 모르겠는???

2022-08-03 02:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +public class ToDoListService {
메서드를 분리하는 건 좋은데, 불필요한 분리는 가독성을 저해합니다ㅜㅜ

2022-08-06 17:19 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +  }
@AllArgsConstructor  lombok 추가했습니다

2022-08-07 12:26 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +  public ResponseEntity<?> postToDo(@RequestBody CreateToDoRequest createToDoRequest) {
리턴으로 HttpStatus.ok을 하기위해 사용했습니다. 자료구조를 통합하기위해 ResponseDto로 ResponseMessage로 리턴하는 방식으로 변경하였습니다.

2022-08-07 12:26 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +    return new ResponseEntity<>("SUCCESS", HttpStatus.OK);
상태 코드를 작성해서 변경하겠습니다.

2022-08-07 12:27 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +  @PutMapping("/{id}")
전체적인 변경이 아니라서 부분 수정인 Patch가 더 적절하다고 생각합니다. 변경하겠습니다.

2022-08-07 12:28 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/domain/ToDoList.java
> +  private LocalDateTime createdDateTime;
생성만 생각하고 지나갔던 것 같습니다. BaseEntity를 사용해서 생성과 수정에 자동화로 바꾸겠습니다.

2022-08-07 12:28 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +
넵 병합하겠습니다!

2022-08-07 12:29 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +}
생성과 수정이 명확하도록 수정하겠습니다.

2022-08-07 12:29 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +  }
좀 더 명확하게 나누어 진행하겠습니다.

2022-08-07 12:33 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +public class ToDoListService {
이번 수정 사항

1.  불필요한 메서드 분리 수정
2.  컨트롤러 리턴 자료형식 통합
3.  baseTime 적용 생성시간 수정시간 자동화
4.  컨트롤러 상태 메서드 적용
5. 스웨거 문서화

리뷰 감사합니다~!

2022-08-07 12:34 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +})
넵!

2022-10-12 12:57 UTC, closed without merging