Harim/working
selab-hs/selab-todo-list pull request #2
Opened 2022-08-08 11:12 UTC by HwangHarim

PR 부탁드려요!

2022-08-08 13:30 UTC, DongGeon0908 reviewed
고생하셨습니다!

2022-08-08 13:30 UTC, DongGeon0908 commented on README.md
>  # SELAB TODO-LIST STUDY
다음부터는 첫번째 PR에 계속 쌓는 식으로 리뷰 요청 부탁드립니다!

2022-08-08 13:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +@AllArgsConstructor
@Requiredargsconstructor 요거 확인 부탁드려요

2022-08-08 13:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/dto/response/UpdateToDoResponse.java
> +@Builder
되도록, 생성할 필드가 3개 이상일때 빌더패턴을 사용!

2022-08-08 13:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/dto/response/CreateToDoResponse.java
> +@Builder
되도록, 생성할 필드가 3개 이상일때 빌더패턴을 사용!

2022-08-08 13:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/dto/request/UpdateToDoRequest.java
> +@NoArgsConstructor
롬복을 쓸때, 어떻게 롬복이 컴파일될때 적용되는지 확인하고 쓰셔용

2022-08-08 13:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/dto/request/CreateToDoRequest.java
> +@Builder
롬복을 쓸때, 어떻게 롬복이 컴파일될때 적용되는지 확인하고 쓰셔용

2022-08-08 13:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/common/dto/ResponseDto.java
> +    }
v1과 v2를 따로 만든 이유가 있을까요?

2022-08-08 13:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/common/converter/ResponseConverter.java
> +  }
두개를 나눈 이유가 궁금해요!

2022-08-08 13:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +  }
없으면 생성인가요?

2022-08-08 13:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +  }
pageDefault를 찾아보세요

2022-08-09 05:54 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/common/converter/ResponseConverter.java
> +  }
하나는 성공 message만을 나타네는 것이고 하는 검색같은 기능의 결과를 postMan으로 data를 확인하기위해 2개로 나누었습니다.

2022-08-09 05:54 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/common/dto/ResponseDto.java
> +    }
위와 같은 이유로 나누었는데 이번 수정해서 통합해보려고 합니다.

2022-08-09 05:54 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/common/dto/ResponseDto.java
> +    }
v1 : response Message만 리턴을 합니다.
v2 : response Message와 데이터를 보여주기위해 두개로 나누어 작성했습니다.
이번 수정에서는 통합되도록 수정해 보겠습니다.

2022-08-09 05:55 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +  }
없으면 오류가 뜨게 수정하겠습니다.

2022-08-09 05:55 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +  }
page Default는 생각을 못했는데 적용해서 커밋하겠습니다.

리뷰 감사합니다.

2022-08-11 16:28 UTC, HwangHarim commented
수정내용

1.  ResponseDto 통합
2. paging  추가
3. 불필요한 롬복 삭제
4. @Requiredargsconstructor 사용

pr 부탁드립니다~!

2022-08-12 03:35 UTC, DongGeon0908 reviewed
고생하셨습니다 몇가지 확인하고 다음 단계로 넘어가시죠

2022-08-12 03:35 UTC, DongGeon0908 commented on README.md
요구사항을 바탕으로 내가 어떤식으로 구현했는지를 작성해주셨으면 합니다

2022-08-12 03:35 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +  }
아직 있네요

2022-08-12 03:35 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +          throw new NullPointerException();
Exception을 추상화해서 사용해보시죠

2022-08-12 03:35 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/common/converter/ResponseConverter.java
> +public class ResponseConverter {
converter를 만든 이유는?

2022-08-12 03:35 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/dto/request/CreateToDoRequest.java
> +@NoArgsConstructor
롬복에 대해 공부해보시길

2022-08-12 03:35 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +  }
반환값에 "ok"가 들어가는게 맞을까요?
프론트 개발자분들에게 너무 불친절한 응답 값 같아요

2022-08-12 03:35 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +    List<ToDoList> toDoLists = toDoListService.getTodos(Sort.by(Direction.ASC, "id"));
정렬 기준을 request로 받는게 좋을 것 같네요

2022-10-05 15:59 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +    List<ToDoList> toDoLists = toDoListService.getTodos(Sort.by(Direction.ASC, "id"));
@PageableDefault 를 사용해서 List로 반환했습니다!

2022-10-05 15:59 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +  }
상세한 설명으로 변경하겠습니다.

2022-10-05 15:59 UTC, Haunbl commented on src/main/java/kr/co/selab/selabtodo/dto/request/CreateToDoRequest.java
> +@NoArgsConstructor
불필요한 롬복 삭제하겟습니다.

2022-10-05 16:00 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/common/converter/ResponseConverter.java
> +public class ResponseConverter {
다시 생각해보니 converter 보다는 handler에 기능을 하는게  더 직관적이라고 생각합니다.

2022-10-05 16:00 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +          throw new NullPointerException();
추상화 진행하겠습니다.

2022-10-05 16:01 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/application/ToDoListService.java
> +  }
pageDefault를 사용해서 변경했습니다!

2022-10-05 16:01 UTC, Haunbl commented on README.md
요구사항 수정하겠습니다.

2022-10-06 13:32 UTC, DongGeon0908 requested changes
전반적으로 많이 개선하셨네요!
그런데 Exception이 터지면 어디서 받을까요?
ControllerAdvice를 한번 찾아보시길!!
해당 부분만 수정하시면 될 듯 합니다

2022-10-09 05:17 UTC, DongGeon0908 requested changes
1. 코드 컨벤션 맞추기 (코드 정리는 기본)
2. Exception Handler에 대해 학습하기
3. Entity를 바로 반환하면 않되는 이유에 대해 공부하기

2022-10-09 05:17 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/common/Handler/ErrorExceptionHandler.java
> +  @ExceptionHandler(NullPointerException.class)
BusinessException은 핸들링 하지 않는 건가요?

2022-10-09 05:17 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/common/Handler/ErrorExceptionHandler.java
> +@ControllerAdvice
RestControllerAdvice

2022-10-09 05:17 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +public class ToDoListController {
Service -> Controller로 데이터를 줄때 엔티티를 왜 반환하는 거죠?
entity를 반환하면 않되는 이유가 무엇일까요?

2022-10-11 16:50 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/common/Handler/ErrorExceptionHandler.java
> +@ControllerAdvice
RestControllerAdvice  / ControllerAdvice 차이를 구분해서 정리하겠습니다!

2022-10-11 18:30 UTC, HwangHarim commented on src/main/java/kr/co/selab/selabtodo/presentation/ToDoListController.java
> +public class ToDoListController {
entity로 반환하게 되면 API 스펙과 엔티티 사이에 의존성이 생기는 문제가 됩니다.  service에도 의존하고 DTO도 의존하고 Entity도 의존하는 Controller가 만들어져서 의존 관계로 볼 때 문제가 됩니다. 그리고 DTO로 리터하면 순환참조를 예방 할 수있습니다.  엔티티를 컨트롤러에서 응답으로 return하게 되면, 엔티티가 참조하고 있는 객체는 지연 로딩되고, 로딩된 객체는 또 다시 본인이 참조하고 있는 객체를 호출하게 되어 문제 될 수 있습니다. 그러므로 entity를 환해서는 안됩니다.

2022-10-12 12:56 UTC, DongGeon0908 reviewed
고생하셨습니다. TODO는 여기서 끝내시죠!
조금 더 공부하고 싶으신다면, 현재 코드에대한 test-code를 작성하시죠

2022-10-12 12:57 UTC, merged