:sparkles: [dev/xx1022] Todo-list 전체적인 구조 설정
selab-hs/selab-todo-list pull request #3
Opened 2022-09-12 07:24 UTC by xx10222

- 엔티티 생성 및 구조 설정
- 기능 구현 끝나고 리뷰어 등록하겠슴둥!

2022-09-17 08:52 UTC, DongGeon0908 requested changes
고려해야 될 것
1. Http Status
2. ResponseEntitiy
3. GlobalExceptionHandeler
4. ControllerAdvice

2022-09-17 08:52 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +@Controller
Rest

2022-09-17 08:52 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +@RequestMapping("/todo/")
/api/todo

2022-09-17 08:52 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +    @GetMapping("")
@GetMapping

2022-09-17 08:52 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +        String result = "모든 할 일이 삭제되었습니다";
???????????????????????????????????

2022-09-17 08:52 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +    @DeleteMapping("")
@DeleteMapping

2022-09-17 08:52 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +        String result = "해당 할 일이 삭제되었습니다";
????????????????????????

2022-09-17 08:52 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +public class TodoController {
생성, 수정, 삭제, 조회 등에 대한 상태코드는?

2022-09-17 08:52 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/model/dto/TodoReq.java
> +public class TodoReq {
TodoRequest

2022-09-17 08:52 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/model/dto/TodosRes.java
> +public class TodosRes {
TodoResponse

2022-09-17 08:52 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/TodoService.java
> +    }
음 이건 조금 더 수정할 수 있을 것 같은데...

2022-09-17 08:52 UTC, DongGeon0908 commented on src/test/java/kr/co/selab/selabtodo/service/TodoServiceTest.java
> +
이러면 DB 연결되어서 테스트하는거 아닌가요?

2022-09-19 18:12 UTC, xx10222 commented on src/test/java/kr/co/selab/selabtodo/service/TodoServiceTest.java
> +
@DongGeon0908 
넹! 로컬에 스키마 하나 만들어서 사용하고 있습니다!
서비스 테스트 코드 작성할 때는 DB 연결 안하고 하는게 더 좋을까요..?

2022-09-21 12:39 UTC, DongGeon0908 commented on src/test/java/kr/co/selab/selabtodo/service/TodoServiceTest.java
> +
mock에 대해 아실까요??

2022-09-23 14:45 UTC, xx10222 commented on src/test/java/kr/co/selab/selabtodo/service/TodoServiceTest.java
> +
한번도 사용해본적 없지만 공부해서 사용해보겠습니다!!

2022-09-23 15:01 UTC, xx10222 commented
> 고려해야 될 것
> 
> 1. Http Status
> 2. ResponseEntitiy
> 3. GlobalExceptionHandeler
> 4. ControllerAdvice

1) https://github.com/xx10222/selab-todo-list/wiki/Http-Status
2) https://github.com/xx10222/selab-todo-list/wiki/ResponseEntity

3번과 4번도 공부해서 적용하고 또 PR 올리겠습니다!

2022-09-24 03:30 UTC, DongGeon0908 reviewed
테스트 코드를 한번 작성해보시죠!!!

2022-09-24 03:30 UTC, DongGeon0908 commented on src/test/java/kr/co/selab/selabtodo/service/TodoServiceTest.java
> +
mock stub에 대해 학습 진행 부탁드립니다

2022-09-24 03:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/TodoService.java
> +    @Transactional(readOnly = true)
readOnly를 붙이는 이유는 무엇 때문일까요?

2022-09-24 03:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/model/dto/UpdateRequest.java
> +public record UpdateRequest(String title, Long order, boolean completed) {
```suggestion
public record UpdateRequest(
        String title, 
        Long order, 
        boolean completed
) {
```

2022-09-24 03:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/model/dto/CreateRequest.java
> +public record CreateRequest(String title, Long order) {
```suggestion
public record CreateRequest(
           String title, 
           Long order
) {
```

2022-09-24 03:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/model/Todo.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
GenerationType에 대해 설명해주세요

2022-09-24 03:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/error/exception/BusinessException.java
> +public abstract class BusinessException extends RuntimeException {
CheckException과 UnCheckedException의 차이에 대해 설명해주세요

2022-09-24 03:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +@RequestMapping("/api/v1/todos/")
어떤 타입으로 받을 거싱고, 어떤 타입으로 제공할 것인지 알려줄 수 있다면 정말 좋을 것 같아요!!

2022-09-24 03:30 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/common/ResponseDto.java
> +public record ResponseDto<T>(T date) implements Serializable {
해당 클래스는 어떤 역할을 할까요?

2022-09-26 10:32 UTC, xx10222 commented on src/main/java/kr/co/selab/selabtodo/service/TodoService.java
> +    @Transactional(readOnly = true)
@DongGeon0908 
읽기 전용 트랜잭션을 사용하면 영속성 컨텍스트에 스냅샷을 보관하지 않아서 읽기 성능이 더 좋아진다고 알고 있습니다!

2022-09-26 10:44 UTC, xx10222 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +@RequestMapping("/api/v1/todos/")
@DongGeon0908  Swagger를 사용해서 해결해도 괜찮을까욤?

2022-09-26 16:09 UTC, xx10222 commented on src/main/java/kr/co/selab/selabtodo/service/TodoService.java
> +    @Transactional(readOnly = true)
https://github.com/xx10222/selab-todo-list/wiki/%EC%9D%BD%EA%B8%B0-%EC%A0%84%EC%9A%A9-%EC%BF%BC%EB%A6%AC%EC%9D%98-%EC%84%B1%EB%8A%A5-%EC%B5%9C%EC%A0%81%ED%99%94

2022-09-29 06:10 UTC, xx10222 commented on src/main/java/kr/co/selab/selabtodo/model/Todo.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
https://github.com/xx10222/selab-todo-list/wiki/JPA-%EA%B8%B0%EB%B3%B8-%ED%82%A4-%EC%83%9D%EC%84%B1-%EC%A0%84%EB%9E%B5

기본키 생성 전략입니다!
4가지 방식이 있는데 저는 그 중에서 IDENTIFY 속성을 사용했습니다!

2022-09-29 06:15 UTC, xx10222 commented on src/main/java/kr/co/selab/selabtodo/error/exception/BusinessException.java
> +public abstract class BusinessException extends RuntimeException {
checkException은 컴파일러가 컴파일 할 때 확인하는 예외이고, uncheckedexception은 컴파일러가 별도로 확인하지 않는 예외입니다

checkedException은 컴파일러를 통해 문제를 잡기 때문에 개발자가 놓치지 않는다는 장점이 있으나, 실제로는 개발자가 모든 체크 예외를 반드시 잡거나 던지도록 처리해야 해서 번거롭습니다

UncheckedException은 컴파일러가 예외를 체크하지 않지만 throws를 선언하지 않고 생략할 수 있기 때문에 신경쓰고 있지 않은 언체크 예외를 무시할 수 있습니다

2022-10-01 16:04 UTC, xx10222 commented on src/main/java/kr/co/selab/selabtodo/common/ResponseDto.java
> +public record ResponseDto<T>(T date) implements Serializable {
응답할 때 보내줄 객체를 담는 DTO 클래스입니당
api 별로 다른 응답 객체들을 이 클래스로 한번 더 감싸서 관리하기 편하다고 생각합니동..!

2022-10-04 12:44 UTC, DongGeon0908 requested changes
어느정도 온 것 같아 다행스럽게 생각합니다 후하후하
조금 더 파이팅

2022-10-04 12:44 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/common/dto/ResponseDto.java
> +    }
conflict면 error code 아닌가요???

2022-10-04 12:44 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/config/SwaggerConfig.java
> +public class SwaggerConfig {
Swagger 명세 좋아요!

2022-10-04 12:44 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +@RequestMapping("/api/v1/todos/")
http의 produce와 consume에 대해 찾아보세용!

2022-10-04 12:44 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +        Todo todo = todoService.getTodo(id);
entity를 바로 외부로 보내느 걸까요??

2022-10-04 12:44 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +
생성의 status code는 무엇일까요?

2022-10-04 12:44 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/error/exception/GlobalExceptionHandler.java
> +    }
Business를 위로 올려야 될 것 같아요
그리고 Runtime은 필요없지 않나요??

추가적으로 그외의 에러는 어떻게 핸들링 하실건가요?

2022-10-04 12:44 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/model/dto/TodosResponse.java
> +    private List<Todo> todos;
엔티티를 바로 내보내는게 맞을까요?

2022-10-09 06:41 UTC, xx10222 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +        Todo todo = todoService.getTodo(id);
dto로 감싸도록 수정하겠슴둥!

2022-10-09 14:48 UTC, DongGeon0908 reviewed
CORS 관련 설정 부탁드립니다.
해당 설정만하시고, TODO는 종료하면 될 것 같네요

2022-10-09 14:48 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/error/exception/GlobalExceptionHandler.java
> +    }
NullPointException이 발생하는 이유가 있을까요?

2022-10-11 06:47 UTC, xx10222 commented
> CORS 관련 설정 부탁드립니다. 해당 설정만하시고, TODO는 종료하면 될 것 같네요

https://github.com/xx10222/selab-todo-list/wiki/CORS
CORS 설정 완료했습니다!

2022-10-11 06:51 UTC, xx10222 commented on src/main/java/kr/co/selab/selabtodo/error/exception/GlobalExceptionHandler.java
> +    }
주로 생성되지 않은 객체에 접근할 때 발생하는데, NullPointException은 언제 어디서 발생할지 모르고 항상 조심해줘야 하는 에러라 예외처리를 해주는 것이 좋다고 생각되어서 추가했습니둥..!

2022-10-11 14:31 UTC, merged