todo-list 코드 리뷰 부탁드립니다.
selab-hs/selab-todo-list pull request #4
Opened 2022-09-28 17:40 UTC by sonrose

아직은 어떻게 해야 할지 감이 잘 안 잡혀서 기본적인 CRUD만 구현하였습니다. 🥲

**controller package**
TodoController: 요청에 따른 작업과 그 결과를 반환한다.

**model package**
TodoEntity: DB를 만들고 DB에 접근한다.
- id: 고유 ID
- title: 할 일 목록
- order: 순서
- checked: 처리 여부

TodoRequest: 요청과 관련된 객체들이다.
TodoResponse: 응답과 관련된 객체들이다.

**repository package**
TodoRepository: JpaRepository를 상속 받는 인터페이스이다.

**service package**
TodoService: repository가 동작하는 로직 부분이다.

2022-09-29 11:10 UTC, DongGeon0908 requested changes
고생하셨습니다.

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +@AllArgsConstructor
해당 어노테이션이 어떤 기능을 하는지 아실까요?
롬복을 무분별하게 쓰는건 좋지 않아요

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +@RequestMapping("/")
Rest API Url 형식에 대해 한번 찾아보세요

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +    @PostMapping("/create")
Rest의 규칙에 대해 확인 부탁드립니다.

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +@RequestMapping("/")
반환타입에 대한 명시를 해주면 좋을 듯 하네요
xml, json 등..

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +            request.setChecked(false);
spring validate로 체크하시죠

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +        log.info("할 일 생성");
왜 로그가 필요한가요?

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +        TodoEntity result = this.service.add(request);
entity를 Controller까지 빼낸 이유가 있을까요?
그리고 this는 생략 해주세요

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +        return ResponseEntity.ok(new TodoResponse(result));
생성할때 상태코드가 200인가요?

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +        log.info("단건 조회");
log 빼주세요

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +                .collect(Collectors.toList());
여기서 dto 말아주는게 맞을까요?
그리고 페이징 처리는요?

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +    @PatchMapping("{id}")
Patch와 Put 차이에 대해 알려주세요

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/controller/TodoController.java
> +    public ResponseEntity<?> delete(@PathVariable Long id) {
반환값이 없으면, Void 아닌가요?
status 코드도 200이 맞을까요?

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/model/TodoEntity.java
> +@AllArgsConstructor
롬복 주위

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/model/TodoEntity.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
id 생성 전략에 대해 아실까요?

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/model/TodoEntity.java
> +    @Column(name = "todoOrder", nullable = false)
sql column은 스네이크 표기법입니다

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/model/TodoResponse.java
> +    private String url;
이건 무엇일까요?

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/TodoService.java
> +        entity.setChecked(request.getChecked());
setter쓰지 말고, 특정 비즈니스 로직을 담당하는 메서드를 만드는건 어떨까요?

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/TodoService.java
> +        TodoEntity entity = new TodoEntity();
생성자로 받을 수 있지 않을까요?

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/TodoService.java
> +        return this.repository.save(entity);
this 빼주세요

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/TodoService.java
> +        }
request에서 validate를 쓰면 해당 로직이 불필요할거에요

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/TodoService.java
> +                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND));
Exception을 재정의할 수 없을까요?
그리고 Exception이 터지고 나서 Advice해주는 곳은 어디있을까요?

2022-09-29 11:10 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/TodoService.java
> +    }
페이징 처리

2022-10-17 15:46 UTC, DongGeon0908 reviewed
몇가지 키워드를 안내해드릴게요 확인하시고 적용해주세요
1. ResponseEntity
2. Rest API
3. Http Status Code
4. RestControllerAdvice
5. ExceptionHandler
6. Swagger

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/domain/Item.java
> +    @Column(name = "todo_order")
todo를 붙일 필요가 있나요?

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/domain/Item.java
> +    }
롬복에 기본생성자 만드는 거 있어요

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/repository/ItemSaveRequestDto.java
> +    }
롬복은 왜 쓰는걸까요?

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/repository/ItemSaveResponseDto.java
> +    }
생성자를 만들어주는 어노테이션이 있습니다

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +@RequestMapping("/items")
rest api에서 보통 어떤 path 규칙을 사용할까요?

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +    public List<Item> items() {
Paging처리는 진행하지 않는 걸까요?

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +        Item item = itemService.findById(itemId).get();
데이터가 없을 경우도 있지 않은가요?

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +        Item item = itemService.findById(itemId).get();
엔티티를 바로 반환하면 않되는 이유에 대해 설명해주세요

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +    @PostMapping("/add")
rest api 규칙에 대해 학습하시고, 수정 부탁드립니다

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +        System.out.println("수정");
logger

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +        itemService.deleteById(itemId);
itemId가 없으면 어떻게 될까요?

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +@RequestMapping("/items")
Swagger 또는 RestDocs를 추가해주세요

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/HomeController.java
> +public class HomeController {
어떤 용도로 쓰는거죠?

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/ItemService.java
> +            updatedItem.setCompleted(updateParam.getCompleted());
Spring Validate

2022-10-17 15:46 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/ItemService.java
> +        Item updatedItem = itemRepository.findById(itemId).orElseThrow();
exception Handling에 대해 찾아보시고, 적용해주세요

2022-10-21 07:48 UTC, sonrose commented on src/main/java/kr/co/selab/selabtodo/domain/Item.java
> +    @Column(name = "todo_order")
mysql에 이미 order 예약어가 있다고 해서 새로 설정했습니다.

2022-10-21 11:05 UTC, sonrose commented on src/main/java/kr/co/selab/selabtodo/service/ItemService.java
> +            updatedItem.setCompleted(updateParam.getCompleted());
살려주세요 모르겠어요

2022-10-22 05:57 UTC, DongGeon0908 requested changes
1. rest api path  규칙 확인하기
2. spring에서 제공하는 valid 확인하기
3. Exception 재정의 (대표적으로는 BusinessException)

2022-10-22 05:57 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/exception/exhandler/advice/ExControllerAdvice.java
> +    }
RuntimeException을 상속한 Exception을 만들어서, 각 상황에 맞게 커스텀해서 사용하는 건 어떨까요?

2022-10-22 05:57 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/ItemService.java
> +            updatedItem.setCompleted(updateParam.getCompleted());
https://www.baeldung.com/spring-valid-vs-validated

키워드 올립니다

2022-10-22 05:57 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +    }
생성할 때는 status가 201아닌가요?

2022-10-22 05:57 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +    @PostMapping("/post/list")
path 이거 맞나요?

2022-10-22 05:57 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +    @DeleteMapping("/delete/{itemId}")
path 이거 맞나요?

2022-10-24 10:51 UTC, DongGeon0908 reviewed
- CORS를 어떻게 제어하실건가요?
- 더티체킹을 적용해주세요

2022-10-24 10:51 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/exception/exhandler/GlobalExceptionHandler.java
> +    }
가장 밑에

2022-10-24 10:51 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/exception/exhandler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
에러가 터졌는데, 왜 터졌을까??하고 사람들이 로깅된 내용을 찾아볼건데요
현재는 로그가 없어서 해당 에러에 대한 추적이 어려울 것 같네요

2022-10-24 10:51 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/ItemService.java
> +        itemRepository.save(updatedItem);
인프런 jpa 강의 들으시지 않았나요?
jpa의 더티체킹에 대해 아실까요?

2022-10-24 10:51 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/ItemService.java
> +        ItemSaveResponseDto savedDto = new ItemSaveResponseDto(savedItem.getId(), savedItem.getTitle(), savedItem.getOrder(), savedItem.getCompleted());
```suggestion
        ItemSaveResponseDto savedDto = new ItemSaveResponseDto(
        savedItem.getId(), 
        savedItem.getTitle(), 
        savedItem.getOrder(), 
        savedItem.getCompleted()
        );
```

2022-10-24 10:51 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +    @DeleteMapping
content가 없을 때 제공하는 status code는 무엇일까요?

2022-10-24 10:51 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +        return ResponseEntity.ok(itemService.findItems());
삭제할 때도 statusCode가 200인가요?

2022-10-24 10:51 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +        return ResponseEntity.ok(itemService.findItems());
그리고 해당 로직은 이상한데요

2022-10-24 10:51 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/web/ItemController.java
> +    }
이전에도 리뷰드린 것 같지만, 엔티티를 바로 반환하지 않아야 합니다.
그 이유에 대해 찾아보세요

2022-10-31 12:32 UTC, DongGeon0908 reviewed
넵 이정도면 된 것 같네요
코드보시면서 이전에 리뷰드린 내용에 대해서만, 체크 부탁드립니다

머지 진행할게요

2022-10-31 12:32 UTC, DongGeon0908 commented on src/main/java/kr/co/selab/selabtodo/service/ItemService.java
> +        return savedDto;
```suggestion
        return new ItemSaveResponseDto(
                savedItem.getId(),
                savedItem.getTitle(),
                savedItem.getOrder(),
                savedItem.getCompleted());
```

2022-10-31 12:33 UTC, merged